server:
  port: 8081
spring:
  application:
    name: premium
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/premium # should be on a different database in a real world e.g.
    username: seebaware
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true